baseURL = "https://adrianpostoaca.github.io/contabilitate-site/"
languageCode = "ro-ro"
title = "Contabilitate și Expertize Financiare"
theme = ""
relativeURLs = true
canonifyURLs = true

[pagination]
  pagerSize = 10

[params]
  description = "Servicii contabile și expertize financiare"
  author = "Numele firmei"
  email = "contact@firma.ro"